package JFRames;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author mantr
 */
public class form433 extends javax.swing.JFrame {
        PreparedStatement pst=null;
        ResultSet rs=null; 
        Connection conn1=null;
        Connection conn2=null;
        static double balance433=0;
        
    /**
     * Creates new form form433
     */
    
    public form433() throws SQLException {
        initComponents();
        Connections();
        Update_table();
        
    }
    
    public void Update_table()
    {
        try{
        String sql="Select * from Team";
        pst=conn1.prepareStatement(sql);
        rs=pst.executeQuery();
        form433table.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        } 
    }
    public void Connections()  throws SQLException
    {
      
     
     try{
         conn1=DriverManager.getConnection("jdbc:mysql://localhost:3306/participant1","root","Mantri@1999");
     }
     catch(SQLException e)
     {}
     
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        stbutton = new javax.swing.JButton();
        rwbutton = new javax.swing.JButton();
        cm1button = new javax.swing.JButton();
        cambutton = new javax.swing.JButton();
        cm2button = new javax.swing.JButton();
        lbbutton = new javax.swing.JButton();
        cb1button = new javax.swing.JButton();
        cb2button = new javax.swing.JButton();
        rbbutton = new javax.swing.JButton();
        gkbutton = new javax.swing.JButton();
        Lwbutton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        form433table = new javax.swing.JTable();
        pointstext = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        baltext = new javax.swing.JTextField();
        Refreshbutton = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 0));

        stbutton.setText("ST");
        stbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stbuttonActionPerformed(evt);
            }
        });

        rwbutton.setText("RW");
        rwbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rwbuttonActionPerformed(evt);
            }
        });

        cm1button.setText("CM");
        cm1button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cm1buttonActionPerformed(evt);
            }
        });

        cambutton.setText("CAM");
        cambutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambuttonActionPerformed(evt);
            }
        });

        cm2button.setText("CM");
        cm2button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cm2buttonActionPerformed(evt);
            }
        });

        lbbutton.setText("LB");
        lbbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbbuttonActionPerformed(evt);
            }
        });

        cb1button.setText("CB");
        cb1button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1buttonActionPerformed(evt);
            }
        });

        cb2button.setText("CB");
        cb2button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2buttonActionPerformed(evt);
            }
        });

        rbbutton.setText("RB");
        rbbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbbuttonActionPerformed(evt);
            }
        });

        gkbutton.setText("GK");
        gkbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gkbuttonActionPerformed(evt);
            }
        });

        Lwbutton.setText("LW");
        Lwbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LwbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(cm1button, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152)
                        .addComponent(cm2button, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(stbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cambutton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(gkbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Lwbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(245, 245, 245)
                                .addComponent(rwbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(cb1button, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cb2button, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(stbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rwbutton)
                    .addComponent(Lwbutton))
                .addGap(82, 82, 82)
                .addComponent(cambutton)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cm2button)
                    .addComponent(cm1button))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbbutton)
                    .addComponent(lbbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb1button)
                    .addComponent(cb2button))
                .addGap(83, 83, 83)
                .addComponent(gkbutton))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 255));

        form433table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Position", "Points", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        form433table.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(form433table);

        pointstext.setEditable(false);
        pointstext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointstextActionPerformed(evt);
            }
        });

        jLabel1.setText("Points");

        jLabel2.setText("Balance");

        baltext.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pointstext)
                    .addComponent(baltext, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pointstext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(baltext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Refreshbutton.setBackground(new java.awt.Color(0, 0, 0));
        Refreshbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Refreshbutton.setForeground(new java.awt.Color(255, 255, 255));
        Refreshbutton.setText("REFRESH");
        Refreshbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Refreshbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(332, 332, 332))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(Refreshbutton)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stbuttonActionPerformed
        ST s1=new ST();
        s1.setVisible(true);
    }//GEN-LAST:event_stbuttonActionPerformed

    private void LwbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LwbuttonActionPerformed
      LW L1=new LW();
      L1.setVisible(true);
    }//GEN-LAST:event_LwbuttonActionPerformed

    private void rwbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rwbuttonActionPerformed
        RW r1=new RW();
        r1.setVisible(true);
    }//GEN-LAST:event_rwbuttonActionPerformed

    private void cambuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambuttonActionPerformed
        CAM cam1=new CAM();
        cam1.setVisible(true);
    }//GEN-LAST:event_cambuttonActionPerformed

    private void cm1buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cm1buttonActionPerformed
        CM cm1=new CM();
        cm1.setVisible(true);
    }//GEN-LAST:event_cm1buttonActionPerformed

    private void cm2buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cm2buttonActionPerformed
       CM cm2=new CM();
       cm2.setVisible(true);
    }//GEN-LAST:event_cm2buttonActionPerformed

    private void lbbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbbuttonActionPerformed
        LB lb1=new LB();
        lb1.setVisible(true);
    }//GEN-LAST:event_lbbuttonActionPerformed

    private void cb1buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1buttonActionPerformed
CB cb1=new CB();
cb1.setVisible(true);
    }//GEN-LAST:event_cb1buttonActionPerformed

    private void cb2buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2buttonActionPerformed
CB cb2=new CB();
cb2.setVisible(true);
    }//GEN-LAST:event_cb2buttonActionPerformed

    private void rbbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbbuttonActionPerformed
RB rb1=new RB();
rb1.setVisible(true);
    }//GEN-LAST:event_rbbuttonActionPerformed

    private void gkbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gkbuttonActionPerformed
GK gk1=new GK();
gk1.setVisible(true);
    }//GEN-LAST:event_gkbuttonActionPerformed

    private void RefreshbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshbuttonActionPerformed
         
        try {
                     

                form433 f10=new form433();
                f10.setVisible(true);
               double total=0;
              double balance=0;
                       int point=0;
                       int count=0;
              for(int i=0;i<form433table.getRowCount();i++)
              {
                  
                double amount = Double.parseDouble(String.valueOf(form433table.getValueAt(i, 4)));
                total+=amount;
                double tp = Double.parseDouble(String.valueOf(form433table.getValueAt(i, 3)));
                point+=tp;
                count++;
              }
             
              balance = 90.00-total;
               
             
              if(balance<0)
              {
              JOptionPane.showMessageDialog(null,"Insufficient Balance!\nClick OK and select another player.","INNSUFFICIENT BALANCE",JOptionPane.ERROR_MESSAGE);
              String lol=String.valueOf(form433table.getValueAt(--count, 1));
            balance=balance433;
               //   System.out.println("balance<0 wala ballance"+ balance);
              String query= "Delete from team where Name= ?";
              pst = conn1.prepareStatement(query);
            pst.setString(1, lol);
           pst.executeUpdate();
           Update_table();
              }
               balance433=balance;
               //System.out.println("Normal balance copy"+balance433);
              baltext.setText(""+balance);
              
              pointstext.setText(""+point);
            } catch (SQLException ex) {
                Logger.getLogger(form433.class.getName()).log(Level.SEVERE, null, ex);
            }
          
     
    }//GEN-LAST:event_RefreshbuttonActionPerformed

    private void pointstextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointstextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pointstextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form433.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form433.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form433.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form433.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new form433().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(form433.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Lwbutton;
    private javax.swing.JButton Refreshbutton;
    private javax.swing.JTextField baltext;
    private javax.swing.JButton cambutton;
    private javax.swing.JButton cb1button;
    private javax.swing.JButton cb2button;
    private javax.swing.JButton cm1button;
    private javax.swing.JButton cm2button;
    private javax.swing.JTable form433table;
    private javax.swing.JButton gkbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton lbbutton;
    private javax.swing.JTextField pointstext;
    private javax.swing.JButton rbbutton;
    private javax.swing.JButton rwbutton;
    private javax.swing.JButton stbutton;
    // End of variables declaration//GEN-END:variables





}
