package JFRames;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author mantr
 */
public class form451 extends javax.swing.JFrame {
    PreparedStatement pst=null;
        ResultSet rs=null; 
        Connection conn1=null;
        static double balance451=0;
    /**
     * Creates new form form451
     */
    public form451() throws SQLException {
        initComponents();
         Connections();
        Update_table();
    }

    public void Update_table()
    {
        try{
        String sql="Select * from Team";
        pst=conn1.prepareStatement(sql);
        rs=pst.executeQuery();
       
        form451table.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e)
        {
          JOptionPane.showMessageDialog(null, e);
        } 
    }
    public void Connections()  throws SQLException
    {
      
     //Connection conn2=null;
     try{
         conn1=DriverManager.getConnection("jdbc:mysql://localhost:3306/participant1","root","Mantri@1999");
         if(conn1!=null)
         {
         }
     }catch(SQLException e)
     {
   
     }
     
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cambutton = new javax.swing.JButton();
        cmbutton = new javax.swing.JButton();
        Lmbutton = new javax.swing.JButton();
        stbutton = new javax.swing.JButton();
        gkbutton = new javax.swing.JButton();
        rbbutton = new javax.swing.JButton();
        cb2button = new javax.swing.JButton();
        cb1button = new javax.swing.JButton();
        lbbutton = new javax.swing.JButton();
        cdmbutton = new javax.swing.JButton();
        Rmbuttpn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        form451table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        baltext = new javax.swing.JTextField();
        pointstext = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 0));

        cambutton.setText("CAM");
        cambutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambuttonActionPerformed(evt);
            }
        });

        cmbutton.setText("CM");
        cmbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbuttonActionPerformed(evt);
            }
        });

        Lmbutton.setText("LM");
        Lmbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LmbuttonActionPerformed(evt);
            }
        });

        stbutton.setText("ST");
        stbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stbuttonActionPerformed(evt);
            }
        });

        gkbutton.setText("GK");
        gkbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gkbuttonActionPerformed(evt);
            }
        });

        rbbutton.setText("RB");
        rbbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbbuttonActionPerformed(evt);
            }
        });

        cb2button.setText("CB");
        cb2button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2buttonActionPerformed(evt);
            }
        });

        cb1button.setText("CB");
        cb1button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1buttonActionPerformed(evt);
            }
        });

        lbbutton.setText("LB");
        lbbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbbuttonActionPerformed(evt);
            }
        });

        cdmbutton.setText("CDM");
        cdmbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdmbuttonActionPerformed(evt);
            }
        });

        Rmbuttpn.setText("RM");
        Rmbuttpn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RmbuttpnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(Lmbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Rmbuttpn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 156, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(gkbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(196, 196, 196))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cb1button, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(cb2button, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(150, 150, 150))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cambutton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cdmbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(225, 225, 225))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(stbutton)
                .addGap(56, 56, 56)
                .addComponent(cambutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lmbutton)
                    .addComponent(Rmbuttpn))
                .addGap(18, 18, 18)
                .addComponent(cmbutton)
                .addGap(63, 63, 63)
                .addComponent(cdmbutton)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbbutton)
                    .addComponent(rbbutton))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb2button)
                    .addComponent(cb1button))
                .addGap(86, 86, 86)
                .addComponent(gkbutton))
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));
        jPanel3.setForeground(new java.awt.Color(0, 0, 255));

        form451table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Position", "Points", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(form451table);

        jLabel1.setText("Points");

        jLabel2.setText("Balance");

        baltext.setEditable(false);

        pointstext.setEditable(false);
        pointstext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointstextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pointstext)
                    .addComponent(baltext, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pointstext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(baltext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("REFRESH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(440, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(350, 350, 350))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbuttonActionPerformed
CM cm1=new CM();
        cm1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_cmbuttonActionPerformed

    private void cb1buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1buttonActionPerformed
CB cb1=new CB();
cb1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_cb1buttonActionPerformed

    private void stbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stbuttonActionPerformed
 ST s1=new ST();
        s1.setVisible(true);    }//GEN-LAST:event_stbuttonActionPerformed

    private void gkbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gkbuttonActionPerformed
GK gk1=new GK();
gk1.setVisible(true);    }//GEN-LAST:event_gkbuttonActionPerformed

    private void rbbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbbuttonActionPerformed
RB rb1=new RB();
rb1.setVisible(true);    }//GEN-LAST:event_rbbuttonActionPerformed

    private void cb2buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2buttonActionPerformed
CB cb2=new CB();
cb2.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_cb2buttonActionPerformed

    private void lbbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbbuttonActionPerformed
  LB lb1=new LB();
        lb1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_lbbuttonActionPerformed

    private void cambuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambuttonActionPerformed
        CAM cam1=new CAM();
        cam1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_cambuttonActionPerformed

    private void cdmbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdmbuttonActionPerformed
CDM cdm1=new CDM();
cdm1.setVisible(true);
    }//GEN-LAST:event_cdmbuttonActionPerformed

    private void LmbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LmbuttonActionPerformed
LM lm1=new LM();
lm1.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_LmbuttonActionPerformed

    private void RmbuttpnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RmbuttpnActionPerformed
RM rm1=new RM();
rm1.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_RmbuttpnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
                form451 f10=new form451();
                f10.setVisible(true);
               double total=0;
              double balance=0;
                       int point=0;
                       int count=0;
              for(int i=0;i<form451table.getRowCount();i++)
              {
                  
                double amount = Double.parseDouble(String.valueOf(form451table.getValueAt(i, 4)));
                total+=amount;
                double tp = Double.parseDouble(String.valueOf(form451table.getValueAt(i, 3)));
                point+=tp;
                count++;
              }
             
              balance = 90.00-total;
              if(balance<0)
              {
               JOptionPane.showMessageDialog(null,"Insufficient Balance!\nClick OK and select another player.","INNSUFFICIENT BALANCE",JOptionPane.ERROR_MESSAGE);
            String lol=String.valueOf(form451table.getValueAt(--count, 1));
            balance=balance451;
              String query= "Delete from team where Name= ?";
              pst = conn1.prepareStatement(query);
            pst.setString(1, lol);
           pst.executeUpdate();
           Update_table();       
              }
               balance451=balance;
              baltext.setText(""+balance);
              pointstext.setText(""+point);
            } catch (SQLException ex) {
                Logger.getLogger(form433.class.getName()).log(Level.SEVERE, null, ex);
            }
           
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pointstextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointstextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pointstextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form451.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form451.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form451.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form451.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new form451().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(form451.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Lmbutton;
    private javax.swing.JButton Rmbuttpn;
    private javax.swing.JTextField baltext;
    private javax.swing.JButton cambutton;
    private javax.swing.JButton cb1button;
    private javax.swing.JButton cb2button;
    private javax.swing.JButton cdmbutton;
    private javax.swing.JButton cmbutton;
    private javax.swing.JTable form451table;
    private javax.swing.JButton gkbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton lbbutton;
    private javax.swing.JTextField pointstext;
    private javax.swing.JButton rbbutton;
    private javax.swing.JButton stbutton;
    // End of variables declaration//GEN-END:variables
}
