package JFRames;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mantr
 */
public class form4321 extends javax.swing.JFrame {
    PreparedStatement pst=null;
        ResultSet rs=null; 
        Connection conn1=null;
        static double balance4321=0;
    /**
     * Creates new form form4321
     */
    public form4321() throws SQLException {
        initComponents();
         Connections();
        Update_table();
    }

    public void Update_table()
    {
        try{
        String sql="Select * from Team";
        pst=conn1.prepareStatement(sql);
        rs=pst.executeQuery();
       
        /*String firstName = rs.getString("Name");
        
       
        String position=rs.getString("Position");
        
        
        
        System.out.format("%s,%s\n", firstName,position);*/
        form4321table.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        } 
    }
    public void Connections()  throws SQLException
    {
      
     //Connection conn2=null;
     try{
         conn1=DriverManager.getConnection("jdbc:mysql://localhost:3306/participant1","root","Mantri@1999");
         if(conn1!=null)
         {
             System.out.println("Connection Successful Participant1");
         }
     }catch(SQLException e)
     {
         System.out.println("Not connected to Participant1");
     }
     
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gkbutton = new javax.swing.JButton();
        rbbutton = new javax.swing.JButton();
        cb2button = new javax.swing.JButton();
        cb1button = new javax.swing.JButton();
        lbbutton = new javax.swing.JButton();
        cdm1button = new javax.swing.JButton();
        cdm2button = new javax.swing.JButton();
        cam2button = new javax.swing.JButton();
        cmbutton = new javax.swing.JButton();
        cam1button = new javax.swing.JButton();
        stbutton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        form4321table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        baltext = new javax.swing.JTextField();
        pointstext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 0));

        gkbutton.setText("GK");
        gkbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gkbuttonActionPerformed(evt);
            }
        });

        rbbutton.setText("RB");
        rbbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbbuttonActionPerformed(evt);
            }
        });

        cb2button.setText("CB");
        cb2button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2buttonActionPerformed(evt);
            }
        });

        cb1button.setText("CB");
        cb1button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1buttonActionPerformed(evt);
            }
        });

        lbbutton.setText("LB");
        lbbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbbuttonActionPerformed(evt);
            }
        });

        cdm1button.setText("CDM");
        cdm1button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdm1buttonActionPerformed(evt);
            }
        });

        cdm2button.setText("CDM");
        cdm2button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdm2buttonActionPerformed(evt);
            }
        });

        cam2button.setText("CAM");
        cam2button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cam2buttonActionPerformed(evt);
            }
        });

        cmbutton.setText("CM");
        cmbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbuttonActionPerformed(evt);
            }
        });

        cam1button.setText("CAM");
        cam1button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cam1buttonActionPerformed(evt);
            }
        });

        stbutton.setText("ST");
        stbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(cdm1button, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(cam1button, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cdm2button, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cam2button, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 156, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(gkbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(196, 196, 196))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cb1button, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(cb2button, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(150, 150, 150))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(214, 214, 214))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(stbutton)
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cam2button)
                    .addComponent(cam1button))
                .addGap(36, 36, 36)
                .addComponent(cmbutton)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdm2button)
                    .addComponent(cdm1button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbbutton)
                    .addComponent(rbbutton))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb2button)
                    .addComponent(cb1button))
                .addGap(86, 86, 86)
                .addComponent(gkbutton))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 255));

        form4321table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Position", "Points", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(form4321table);

        jLabel1.setText("Points");

        baltext.setEditable(false);

        pointstext.setEditable(false);
        pointstext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointstextActionPerformed(evt);
            }
        });

        jLabel2.setText("Balance");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pointstext)
                    .addComponent(baltext, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pointstext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(baltext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("REFRESH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(387, 387, 387))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb1buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1buttonActionPerformed
CB cb1=new CB();
cb1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_cb1buttonActionPerformed

    private void cmbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbuttonActionPerformed
CM cm1=new CM();
        cm1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_cmbuttonActionPerformed

    private void stbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stbuttonActionPerformed
 ST s1=new ST();
        s1.setVisible(true);    }//GEN-LAST:event_stbuttonActionPerformed

    private void gkbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gkbuttonActionPerformed
GK gk1=new GK();
gk1.setVisible(true);    }//GEN-LAST:event_gkbuttonActionPerformed

    private void rbbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbbuttonActionPerformed
RB rb1=new RB();
rb1.setVisible(true);    }//GEN-LAST:event_rbbuttonActionPerformed

    private void cb2buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2buttonActionPerformed
CB cb2=new CB();
cb2.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_cb2buttonActionPerformed

    private void lbbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbbuttonActionPerformed
  LB lb1=new LB();
        lb1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_lbbuttonActionPerformed

    private void cam2buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cam2buttonActionPerformed
        CAM cam2=new CAM();
        cam2.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_cam2buttonActionPerformed

    private void cam1buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cam1buttonActionPerformed
        CAM cam1=new CAM();
        cam1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_cam1buttonActionPerformed

    private void cdm1buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdm1buttonActionPerformed
CDM cdm1=new CDM();
cdm1.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_cdm1buttonActionPerformed

    private void cdm2buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdm2buttonActionPerformed
     CDM cdm2=new CDM();
cdm2.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_cdm2buttonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

       
        try {
                     

                form451 f10=new form451();
                f10.setVisible(true);
               double total=0;
              double balance=0;
                       int point=0;
                       int count=0;
              for(int i=0;i<form4321table.getRowCount();i++)
              {
                  
                double amount = Double.parseDouble(String.valueOf(form4321table.getValueAt(i, 4)));
                total+=amount;
                double tp = Double.parseDouble(String.valueOf(form4321table.getValueAt(i, 3)));
                point+=tp;
                count++;
              }
             
              balance = 90.00-total;
               
             
              if(balance<0)
              {
            JOptionPane.showMessageDialog(null,"Insufficient Balance!\nClick OK and select another player.","INNSUFFICIENT BALANCE",JOptionPane.ERROR_MESSAGE);
            String lol=String.valueOf(form4321table.getValueAt(--count, 1));
            balance=balance4321;
                 
              String query= "Delete from team where Name= ?";
              

              pst = conn1.prepareStatement(query);
            pst.setString(1, lol);
           pst.executeUpdate();
           Update_table();
            
            
       
              }
               balance4321=balance;
              baltext.setText(""+balance);
              pointstext.setText(""+point);
            } catch (SQLException ex) {
                Logger.getLogger(form433.class.getName()).log(Level.SEVERE, null, ex);
            }
           
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void pointstextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointstextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pointstextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form4321.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form4321.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form4321.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form4321.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new form4321().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(form4321.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField baltext;
    private javax.swing.JButton cam1button;
    private javax.swing.JButton cam2button;
    private javax.swing.JButton cb1button;
    private javax.swing.JButton cb2button;
    private javax.swing.JButton cdm1button;
    private javax.swing.JButton cdm2button;
    private javax.swing.JButton cmbutton;
    private javax.swing.JTable form4321table;
    private javax.swing.JButton gkbutton;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lbbutton;
    private javax.swing.JTextField pointstext;
    private javax.swing.JButton rbbutton;
    private javax.swing.JButton stbutton;
    // End of variables declaration//GEN-END:variables
}
